#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""查大词的习语收全了没有。

audit-ab 只查得出「A 教过而 B 没有」的，A 只收 3002 个高频词，
两表共有的才 517 条 —— A 没收的词依然没有尺子。corner 漏掉的
turn the corner / cut corners / just around the corner /
out of the corner of one's eye 就属于这一类，是手工翻出来的。

这个脚本把「知识」和「核对」分开：清单由人写（下面的 CHECK），
机器负责查 B 里有没有。写完一个字母段的大词，就往 CHECK 里
补一批，跑一遍，缺什么补什么。
首跑（2026-09-05）查 23 个 c 段大词的 101 条习语，缺 34 条，已全部补上。

用法：python3 scripts/audit-idioms.py
"""
import sys, re, unicodedata, importlib.util as u
spec = u.spec_from_file_location('ap', 'scripts/audit-padding.py')
ap = u.module_from_spec(spec); spec.loader.exec_module(ap)

def fold(s):
    s = unicodedata.normalize('NFD', s)
    s = ''.join(c for c in s if unicodedata.category(c) != 'Mn')
    return re.sub(r'[^a-z0-9]+', ' ', s.lower()).strip()

CHECK = {
 # get 一族 —— 写 get 之前先把 coverage 的 42 条待推迟短语列进来（2026-09-12）
 'get': ['get across', 'get along', 'get around', 'get around to', 'get at',
         'get away', 'get away with', 'get back', 'get back at', 'get back together',
         'get by', 'get down', 'get down to', 'get in', 'get in on', 'get in with',
         'get into', 'get off', 'get off on', 'get off with', 'get on', 'get on to',
         'get on with', 'get out', 'get out of', 'get over', 'get over yourself',
         'get round', 'get round to', 'get through', 'get through to',
         'get through with', 'get to', 'get together', 'get up', 'get up as',
         'get up to', 'get ahead', 'get behind', 'get about', 'get above yourself',
         'get-go', 'get-up-and-go'],
 'gospel': ['the gospel truth', 'take something as gospel', 'gospel music'],
 'gossip': ['a gossip column', 'idle gossip'],
 'gouge': ['gouge out'],
 # ha- 段 —— 动笔前先列清单（2026-09-20）
 'habit': ['be in the habit of', 'break a habit', 'a creature of habit',
           'kick the habit'],
 'hack': ['hack it'],
 'hair': ['let your hair down', 'split hairs', 'not turn a hair',
          'a bad hair day'],
 'half': ['your better half', 'go halves', 'not half bad', 'half the time',
          'go off half-cocked', 'at half-mast', 'half measures',
          'too clever by half', 'half a mind to'],
 'hand': ['at hand', 'by hand', 'change hands', 'get out of hand',
          'hand in hand', 'have your hands full', 'on the other hand',
          'out of hand', 'hands down', 'wash your hands of'],
 'handle': ['fly off the handle', 'get a handle on'],
 'hang': ['hang about', 'hang around', 'hang back', 'hang on', 'hang out',
          'hang up', 'get the hang of', 'hang in there'],
 'happy': ['many happy returns', 'happy hour'],
 'hard': ['hard and fast', 'hard up', 'hard done by', 'no hard feelings'],
 'hat': ['at the drop of a hat', 'take your hat off to somebody',
         'keep something under your hat', 'old hat', 'as mad as a hatter'],
 # gu- 与 gy- 段 —— 动笔前先列清单（2026-09-20）
 'guard': ['catch somebody off guard', 'be on your guard', 'stand guard',
           'let your guard down'],
 'guess': ['your guess is as good as mine', 'at a guess', 'guess what',
           'keep somebody guessing'],
 'guest': ['be my guest'],
 'guide': ['a guided tour'],
 'guilt': ['a guilt trip'],
 'guilty': ['plead guilty', 'a guilty conscience', 'find somebody guilty'],
 'gun': ['jump the gun', 'stick to your guns', 'a smoking gun',
         'the big guns', 'under the gun'],
 'gut': ['a gut feeling', 'hate somebody\'s guts', 'bust a gut',
         'spill your guts'],
 'guy': ['you guys'],
 # gr- 段 —— 动笔前先列清单（2026-09-20）
 'grab': ['up for grabs', 'grab a bite'],
 'grace': ['say grace', 'with good grace', 'fall from grace',
           'a grace period', 'a saving grace'],
 'grade': ['make the grade'],
 'grain': ['a grain of truth', 'against the grain',
           'take something with a pinch of salt'],
 'grand': ['a grand total', 'a grand slam', 'a grand piano', 'a grand jury'],
 'grant': ['take something for granted'],
 'grasp': ['grasp the nettle', 'within your grasp'],
 'grass': ['the grass is always greener', 'grass roots', 'a snake in the grass'],
 'grave': ['turn in your grave', 'from the cradle to the grave'],
 'great': ['a great deal', 'no great shakes', 'the great outdoors',
           'great minds think alike'],
 'green': ['the green light', 'green with envy', 'green fingers'],
 'grief': ['come to grief'],
 'grind': ['grind to a halt', 'an axe to grind', 'the daily grind'],
 'grip': ['get a grip', 'come to grips with', 'lose your grip'],
 'ground': ['break new ground', 'get off the ground', 'stand your ground',
            'common ground', 'on the ground'],
 'grow': ['grow up', 'grow on somebody', 'grow out of', 'grow apart',
          'grow into'],
 'grudge': ['bear a grudge'],
 # good —— 核心词，动笔前先列清单（2026-09-20）
 'good': ['be good at', 'be good for', 'do good', 'for good',
          'for the good of', 'as good as', 'make good', 'good for you',
          'in good time', 'a good deal of', 'too good to be true',
          'so far so good', 'as good as gold', 'good riddance',
          'good grief', 'it is a good job', 'what is the good of',
          'good morning', 'good day', 'good evening',
          'good-looking', 'good looks', 'good-natured', 'good nature',
          'good-humoured', 'good humour', 'good-tempered', 'good-hearted',
          'good-for-nothing', 'good sense', 'good name',
          'a good fairy', 'a good old boy'],
 # go- 段 —— 核心词 go 动笔前先列清单（2026-09-20）
 'go': ['go about', 'go after', 'go against', 'go ahead', 'go along',
        'go along with', 'go around', 'go around with', 'go at', 'go away',
        'go back', 'go back on', 'go back to', 'go before', 'go by',
        'go down', 'go down with', 'go for', 'go forward', 'go in',
        'go in for', 'go in with', 'go into', 'go off', 'go off with',
        'go on', 'go on to', 'go out', 'go out of', 'go out to',
        'go out with', 'go over', 'go over to', 'go round', 'go round with',
        'go through', 'go through with', 'go to', 'go together', 'go towards',
        'go under', 'go up', 'go well', 'go with', 'go without',
        'have a go', 'on the go', 'make a go of', 'from the word go',
        'anything goes', 'it goes without saying', 'go easy on', 'go it alone',
        'a go-between', 'a go-getter', 'a go-slow'],
 # gn- 段 —— 动笔前先列清单（2026-09-20）
 'gnaw': ['gnaw at', 'gnaw away at'],
 'gnash': ['gnash your teeth', 'gnashing of teeth'],
 'gnome': ['a garden gnome', 'the gnomes of Zurich'],
 # gl- 段 —— 动笔前先列清单（2026-09-20）
 'glove': ['fit like a glove', 'the gloves are off', 'hand in glove',
           'a glove compartment'],
 'glance': ['at a glance', 'at first glance', 'glance off'],
 'glass': ['a glass ceiling', 'raise a glass', 'people who live in glass houses'],
 'glad': ['glad rags', 'glad-hand', 'be glad to'],
 'glory': ['glory days', 'glory in', 'in your glory'],
 'gloss': ['gloss over'],
 'gloom': ['doom and gloom'],
 'glut': ['a glut of'],
 'glutton': ['a glutton for punishment'],
 'glitter': ['all that glitters is not gold'],
 'global': ['global warming', 'the global village'],
 'gleam': ['a gleam in somebody\'s eye'],
 'glow': ['glow with pride'],
 # gi- 段 —— 动笔前先列清单（2026-09-20）
 'give': ['give and take', 'give or take', 'give way', 'give rise to',
          'give birth to', 'give somebody a hand', 'give as good as you get',
          'give it a rest', 'give the game away', 'give away', 'give back',
          'give in', 'give off', 'give out', 'give over', 'give up',
          'give up on', 'not give a damn'],
 'gift': ['the gift of the gab', 'a gift for something',
          'look a gift horse in the mouth'],
 'gild': ['gild the lily'],
 'gill': ['to the gills', 'green about the gills'],
 'giggle': ['get the giggles', 'for a giggle'],
 'giant': ['a gentle giant', 'a giant leap'],
 'giddy': ['the giddy heights'],
 'gist': ['get the gist'],
 'gird': ['gird your loins'],
 'girl': ['a girl band', 'girl power'],
 'gin': ['a gin and tonic'],
 'ginger': ['ginger up'],
 'given': ['given that', 'take something as a given'],
 # gh- 段 —— 动笔前先列清单（2026-09-20）
 'ghost': ['give up the ghost', 'a ghost of a chance', 'lay the ghost of',
           'a ghost town', 'a ghost story', 'a ghost train'],
 'ghetto': ['a ghetto blaster'],
 'ghastly': ['a ghastly mistake'],
 'ghoulish': ['ghoulish curiosity'],
 'gentle': ['a gentle reminder'],
 'genuine': ['the genuine article'],
 'genius': ['a stroke of genius'],
 'genetics': ['the genetics of'],
 'general': ['in general', 'a general election', 'as a general rule'],
 'generation': ['the younger generation', 'generation gap',
                'from generation to generation'],
 'gender': ['gender equality'],
 'gear': ['get into gear', 'change gear'],
 'geek': ['a computer geek'],
 'gather': ['gather speed', 'gather dust'],
 'gauntlet': ['throw down the gauntlet', 'run the gauntlet'],
 'gaze': ['gaze at'],
 'gasp': ['gasp for breath', 'the last gasp'],
 'gate': ['the departure gate', 'gate money'],
 'garage': ['a garage sale', 'a garage band'],
 'gas': ['step on the gas', 'a gas mask', 'run out of gas',
         'a gas station', 'a gas guzzler'],
 'garment': ['an outer garment'],
 'gap': ['bridge the gap', 'a generation gap', 'a gap year', 'gap-toothed'],
 'garden': ['lead somebody up the garden path', 'a garden party',
            'garden-variety'],
 'gape': ['gape at'],
 'game': ['play the game', 'give the game away', 'fair game',
          'a game plan', 'a game changer', 'ahead of the game',
          'the name of the game', 'a game show', 'game theory'],
 'gamble': ['a gamble on', 'gamble away'],
 'gang': ['gang up on', 'gang together'],
 'gallery': ['play to the gallery'],
 'gallop': ['at a gallop'],
 'gambit': ['an opening gambit'],
 'formula': ['a magic formula'],
 'former': ['the former'],
 'formation': ['fly in formation'],
 'gaffe': ['make a gaffe'],
 'gadget': ['a handy gadget'],
 'future': ['in the future', 'in future', 'the foreseeable future'],
 'fuzzy': ['fuzzy logic'],
 'gag': ['a running gag'],
 'gain': ['gain ground', 'no pain, no gain', 'gain on', 'gain in'],
 'further': ['further to'],
 'fuss': ['make a fuss', 'kick up a fuss', 'fuss over'],
 'fury': ['in a fury'],
 'fuse': ['blow a fuse', 'a short fuse'],
 'funny': ['funnily enough', 'a funny feeling'],
 'furious': ['be furious with'],
 'furniture': ['a piece of furniture'],
 'function': ['a function of'],
 'fund': ['raise funds'],
 'funeral': ['a funeral service'],
 'full': ['full of', 'in full', 'to the full'],
 'fun': ['make fun of', 'for fun'],
 'fulfil': ['fulfil a promise'],
 'fruition': ['come to fruition'],
 'fry': ['out of the frying pan'],
 'frustration': ['out of frustration'],
 'fuck': ['fuck up', 'fuck off'],
 'fuel': ['add fuel to the fire'],
 'front': ['in front of', 'up front', 'a front runner'],
 'frost': ['a hard frost'],
 'frown': ['frown on'],
 'fruit': ['bear fruit', 'the fruits of'],
 'fritter': ['fritter away'],
 'fro': ['to and fro'],
 'frog': ['a frog in your throat'],
 'frolic': ['frolic about'],
 'friend': ['make friends', 'a close friend', 'be friends with'],
 'fright': ['take fright', 'stage fright'],
 'frighten': ['frighten off'],
 'fringe': ['on the fringe of', 'a fringe benefit'],
 'frill': ['no frills'],
 'fresh': ['fresh air', 'make a fresh start', 'fresh out of'],
 'fret': ['fret about'],
 'Freudian': ['a Freudian slip'],
 'Friday': ['Good Friday'],
 'freeze': ['freeze over', 'a pay freeze'],
 'freezing': ['freezing point'],
 'French': ['French window', 'French bread', 'French toast'],
 'frenzy': ['a feeding frenzy', 'a media frenzy'],
 'frequent': ['a frequent flyer'],
 'free': ['for free', 'free of charge', 'set somebody free', 'feel free'],
 'freedom': ['freedom of speech'],
 'freelance': ['work freelance'],
 'fraud': ['commit fraud'],
 'fray': ['enter the fray'],
 'freak': ['a freak accident', 'freak out'],
 'fraught': ['fraught with'],
 'frazzle': ['worn to a frazzle'],
 'frame': ['frame of mind', 'frame of reference', 'a frame-up'],
 'frank': ['to be frank', 'frankly speaking'],
 'fragment': ['fragments of'],
 'fox': ['a sly old fox'],
 'fraction': ['a fraction of a second'],
 'fracture': ['a hairline fracture'],
 'fragile': ['a fragile peace'],
 'fortune': ['make a fortune', 'cost a fortune', 'a small fortune'],
 'forward': ['look forward to', 'put something forward'],
 'foul': ['foul play', 'foul up'],
 'foundation': ['lay the foundations'],
 'four': ['on all fours'],
 'fort': ['hold the fort'],
 'forte': ["somebody's forte"],
 'forth': ['back and forth', 'and so forth'],
 'fortitude': ['show fortitude'],
 'forget': ['forget about', 'forget it'],
 'forgive': ['forgive and forget'],
 'fork': ['fork out'],
 'form': ['in the form of', 'on form', 'a matter of form'],
 'forlorn': ['a forlorn hope'],
 'forge': ['forge ahead'],
 'forever': ['last forever', 'take forever'],
 'foresight': ['have the foresight to'],
 'foreseeable': ['the foreseeable future'],
 'foretaste': ['a foretaste of things to come'],
 'foreign': ['a foreign body', 'foreign policy'],
 'foregone': ['a foregone conclusion'],
 'forefront': ['at the forefront of'],
 'foremost': ['first and foremost'],
 'forelock': ['touch your forelock'],
 'force': ['by force', 'in force', 'join forces', 'the armed forces', 'a force for good'],
 'fore': ['come to the fore'],
 'forecast': ['the weather forecast'],
 'forbidden': ['forbidden fruit'],
 'footsie': ['play footsie'],
 'footprint': ['a carbon footprint'],
 'forbid': ['God forbid'],
 'foray': ['a foray into politics'],
 'fool': ['fool around', "fool's gold", "a fool's paradise", 'make a fool of yourself', 'play the fool'],
 'foot': ['on foot', 'put your foot down', 'foot the bill', 'get off on the wrong foot', 'under your feet'],
 'football': ['a political football'],
 'footing': ['on an equal footing', 'lose your footing', 'on a war footing'],
 'foothold': ['gain a foothold'],
 'follow': ['follow suit', 'as follows', "follow in somebody's footsteps"],
 'food': ['food for thought', 'off your food'],
 'font': ['a font of knowledge'],
 'focus': ['the focus of attention', 'in focus', 'out of focus', 'focus on'],
 'fog': ['in a fog'],
 'foggy': ['not have the foggiest idea'],
 'fold': ['fold your arms', 'return to the fold', 'fold up'],
 'foil': ['a foil to'],
 'fodder': ['cannon fodder'],
 'fly': ['fly off the handle', 'let fly', 'fly in the face of', 'with flying colours'],
 'flutter': ['a flutter of'],
 'flux': ['in a state of flux'],
 'flow': ['go with the flow'],
 'flower': ['in flower', 'a bunch of flowers'],
 'flotsam': ['flotsam and jetsam'],
 'flood': ['a flash flood', 'in floods of tears'],
 'floodgate': ['open the floodgates'],
 'floor': ['take the floor', 'the shop floor'],
 'fling': ['have a fling'],
 'flip': ['flip out', 'flip through'],
 'float': ['float an idea'],
 'flog': ['flog a dead horse'],
 'flesh': ['in the flesh', 'flesh out', 'flesh and blood'],
 'flight': ['take flight', 'a flight of stairs'],
 'flea': ['a flea market', 'a flea in your ear'],
 'flavour': ['add flavour'],
 'flat': ['flat out', 'flat broke'],
 'flattery': ['flattery will get you nowhere'],
 'flame': ['burst into flames', 'go up in flames', 'an old flame'],
 'flash': ['in a flash', 'a flash in the pan'],
 'flap': ['in a flap'],
 'flag': ['fly the flag', 'flag down'],
 'flair': ['have a flair for'],
 'flak': ['take flak'],
 'fit': ['see fit', 'fit in', 'keep fit', 'fit for purpose'],
 'fix': ['in a fix', 'a quick fix'],
 'fist': ['make a good fist of', 'hand over fist'],
 'first': ['at first', 'first of all', 'first come, first served'],
 'fish': ['a fish out of water', 'fish and chips'],
 'fire': ['catch fire', 'set fire to', 'on fire', 'under fire', 'open fire', 'play with fire'],
 'fine': ['cut it fine', 'a fine line'],
 'finger': ['keep your fingers crossed', 'put your finger on', 'point the finger at'],
 'fingertip': ['at your fingertips'],
 'find': ['find out', 'find your feet'],
 'filter': ['filter out', 'filter through'],
 'file': ['on file', 'file for', 'in single file'],
 'fill': ['fill in', 'fill up', 'fill the bill', 'eat your fill'],
 'film': ['a film star'],
 'fight': ['put up a fight', 'fight a losing battle', 'fight back', 'fight off'],
 'figure': ['figure out', 'a figure of speech', 'cut a figure'],
 'fig': ['not give a fig'],
 'fiddle': ['on the fiddle', 'play second fiddle'],
 'field': ['take the field', 'a level playing field', 'play the field'],
 'few': ['quite a few', 'a good few', 'few and far between'],
 'fever': ['a high fever', 'run a fever'],
 'fence': ['sit on the fence', 'mend fences'],
 'fettle': ['in fine fettle'],
 'fetch': ['fetch and carry'],
 'fear': ['for fear of', 'no fear', 'fear the worst'],
 'feast': ['feast your eyes on'],
 'feather': ['a feather in your cap', 'as light as a feather', 'feather your nest'],
 'feel': ['feel like', 'feel free', 'feel your age', 'get the feel of'],
 'feed': ['feed up', 'off your feed'],
 'fee': ['a flat fee'],
 'fault': ['find fault with', 'at fault', 'to a fault'],
 'favour': ['in favour of', 'do somebody a favour', 'curry favour'],
 'fat': ['chew the fat', 'a fat lot of good'],
 'fate': ['tempt fate', "seal somebody's fate"],
 'father': ['the father of'],
 'fashion': ['in fashion', 'out of fashion', 'after a fashion'],
 'fast': ['fast asleep', 'play fast and loose', 'hold fast'],
 'family': ['run in the family', 'start a family', 'a family tree'],
 'famous': ['famous last words'],
 'fancy': ['take a fancy to', 'tickle your fancy', 'fancy dress', 'fancy that'],
 'far': ['as far as', 'by far', 'so far', 'far from', 'far and wide'],
 'face': ['keep a straight face', 'lose face', 'save face', 'face to face',
          'in the face of', 'on the face of it', "face the music", 'pull a face'],
 'fact': ['in fact', 'as a matter of fact', 'the fact of the matter', 'facts and figures'],
 'fail': ['without fail'],
 'fair': ['fair enough', 'fair and square', "it's not fair", 'more than your fair share'],
 'faith': ['in good faith', 'have faith in', 'break faith with'],
 'fall': ['fall in love', 'fall short of', 'fall into place', 'fall flat', 'fall apart'],
 'eye': ['keep an eye on', 'see eye to eye', 'turn a blind eye', "catch somebody's eye",
         'an eye for an eye', 'have your eye on', 'the eye of the storm'],
 'eyebrow': ['raise an eyebrow'],
 'eyelid': ['not bat an eyelid'],
 'eyelash': ['flutter your eyelashes'],
 'extreme': ['in the extreme', 'go to extremes', 'take something to extremes'],
 'explode': ['explode a myth'],
 'explore': ['explore every avenue'],
 'express': ['express yourself', 'express an interest'],
 'expression': ['freedom of expression', 'find expression in'],
 'extend': ['extend an invitation'],
 'extent': ['to some extent', 'to a certain extent', 'to a large extent', 'to what extent'],
 'expect': ['be expecting', 'what do you expect'],
 'expectation': ['live up to expectations', 'contrary to expectation', 'exceed expectations'],
 'expense': ['at the expense of', "at somebody's expense", 'go to the expense of', 'spare no expense'],
 'experience': ['from experience', 'in my experience'],
 'explain': ['explain yourself', 'explain away'],
 'each': ['each and every'],
 'exercise': ['take exercise', 'exercise your right', 'a paper exercise'],
 'exhaust': ['exhaust fumes', 'be exhausted'],
 'exhibit': ['be on exhibit'],
 'exist': ['cease to exist'],
 'example': ['for example', 'set an example', 'make an example of', "follow somebody's example"],
 'exception': ['with the exception of', 'without exception', 'make an exception'],
 'excuse': ['make excuses', 'excuse me'],
 'exchange': ['in exchange for'],
 'even': ['break even', 'even so', 'even though', 'get even', 'even if'],
 'ever': ['ever since', 'hardly ever', 'for ever'],
 'every': ['every other', 'every now and then', 'every bit as'],
 'event': ['in the event of', 'at all events', 'in any event'],
 'evidence': ['give evidence', 'be in evidence'],
 'evil': ['the lesser of two evils', 'speak evil of'],
 'essence': ['in essence', 'of the essence'],
 'establish': ['establish yourself'],
 'esteem': ['hold somebody in high esteem', 'self-esteem'],
 'err': ['err on the side of'],
 'error': ['trial and error', 'in error', 'a margin of error'],
 'errand': ['run an errand', "a fool's errand"],
 'equal': ['on equal terms', 'be equal to', 'all things being equal', 'have no equal'],
 'equation': ['part of the equation'],
 'end': ['in the end', 'at the end of the day', 'make ends meet', 'come to an end',
         'no end of', 'end up'],
 'enough': ['enough is enough', 'fair enough', 'sure enough'],
 'enjoy': ['enjoy yourself'],
 'entrance': ['make an entrance'],
 'embarrassment': ['an embarrassment of riches'],
 'emergency': ['in an emergency', 'a state of emergency'],
 'emphasis': ['put emphasis on', 'the emphasis is on'],
 'empty': ['on an empty stomach'],
 'elbow': ['elbow room', 'elbow grease', 'rub elbows with', 'give somebody the elbow',
           'elbow your way'],
 'element': ['in your element', 'brave the elements', 'the elements'],
 'else': ['or else', 'something else', 'somebody else'],
 'elephant': ['a white elephant', 'the elephant in the room'],
 'eleventh': ['at the eleventh hour'],
 'effect': ['take effect', 'come into effect', 'in effect', 'to that effect',
            'put something into effect'],
 'egg': ['put all your eggs in one basket', 'a bad egg', 'have egg on your face',
         'egg somebody on'],
 'either': ['either way', 'either... or'],
 'ebb': ['the ebb and flow', 'at a low ebb'],
 'echo': ['echoes of'],
 'eclipse': ['in eclipse'],
 'economy': ['economies of scale', 'a false economy'],
 'edge': ['on edge', 'on the edge of', 'have the edge over', 'take the edge off',
          'edge out', 'set your teeth on edge'],
 'educate': ['educate somebody about something'],
 'ear': ['play it by ear', 'be all ears', 'go in one ear and out the other',
         "have somebody's ear", 'keep your ear to the ground', 'up to your ears in',
         'music to your ears', 'turn a deaf ear'],
 'early': ['an early bird', 'at the earliest', 'early days', 'bright and early', 'early on'],
 'earn': ['earn a living', 'earn your keep'],
 'earth': ['cost the earth', 'down to earth', 'on earth', 'move heaven and earth',
           'run somebody to earth'],
 'ease': ['at ease', 'ill at ease', 'with ease', 'put somebody at their ease'],
 'easy': ['take it easy', 'easier said than done', 'go easy on', 'easy come, easy go',
          'easy does it', 'free and easy', 'within easy reach'],
 'eat': ['eat your words', 'eat out of somebody\'s hand', "what's eating",
         'eat like a horse', 'eat your heart out'],

 'call': ['call it a day', 'call the shots', 'call off', 'call for', 'on call',
          'a close call', "call somebody's bluff", 'call in'],
 'carry': ['carry on', 'carry out', 'get carried away', 'carry weight', 'carry the can'],
 'case': ['in case', 'in any case', 'in that case', 'a case in point', 'make a case for'],
 'cast': ['cast doubt on', 'cast a shadow', 'cast off', "cast one's mind back"],
 'catch': ['catch on', 'catch up', 'catch out', 'catch fire', "catch somebody's eye"],
 'chance': ['by chance', 'take a chance', 'stand a chance', 'the chances are',
            'a fighting chance'],
 'change': ['change hands', "change one's mind", 'small change', 'a change of heart',
            'for a change'],
 'check': ['check in', 'check out', 'check up on', 'keep in check', 'a rain check'],
 'chip': ['chip in', "a chip on one's shoulder", 'when the chips are down'],
 'clear': ['clear up', 'clear out', 'clear the air', 'in the clear', 'steer clear of',
           'clear-cut'],
 'close': ['close down', 'close in', 'a close shave', 'close ranks', 'behind closed doors'],
 'cold': ['cold feet', 'in cold blood', 'the cold shoulder', 'out in the cold', 'cold turkey'],
 'come': ['come across', 'come up with', 'come to terms with', 'come what may',
          'come clean', 'come of age', 'come around'],
 'company': ['keep somebody company', 'part company', 'in good company'],
 'contact': ['make contact', 'lose contact'],
 'control': ['out of control', 'under control', 'take control', 'lose control'],
 'cool': ["lose one's cool", 'a cool million', 'be cool with', 'cool it'],
 'corn': ['corn on the cob'],
 'corner': ['turn the corner', 'cut corners', 'just around the corner',
            "out of the corner of one's eye", 'a corner shop'],
 'count': ["count one's blessings", 'count for nothing', 'at the last count'],
 # course 与 cover 写到了（2026-09-05），加回清单
 'course': ['of course', 'in due course', 'a matter of course', 'run its course',
            'on course', 'off course'],
 'cover': ['cover up', 'cover for', 'under cover', "cover one's tracks",
           'from cover to cover'],
 'courage': ['pluck up courage', 'Dutch courage',
             "the courage of one's convictions"],
 'cow': ['till the cows come home', 'a sacred cow', 'have a cow'],
 'court': ['take somebody to court', 'court disaster', 'go to court'],
 # cr 段（2026-09-05 写到 crevice）
 'crack': ['crack down on', 'crack up', 'at the crack of dawn',
           'crack a joke', 'have a crack at'],
 'crash': ['crash a party', 'crash into'],
 'crazy': ['be crazy about', 'like crazy'],
 'cream': ['the cream of the crop', 'cream off'],
 'credit': ['take credit for', 'give somebody credit for',
            'on credit', 'in credit'],
 'creep': ['give somebody the creeps', 'creep up on'],
 'crest': ['crestfallen', 'the crest of a wave'],
 'cricket': ['not cricket'],
 'crime': ['commit a crime', 'organized crime'],
 'critical': ['be critical of', 'critical thinking', 'in a critical condition'],
 'crocodile': ['crocodile tears'],
 'crop': ['crop up', 'come a cropper'],
 'crook': ['the crook of one s arm'],
 'cross': ["cross one's mind", 'cross swords with', 'at cross purposes',
           'cross out', 'be cross with'],
 'crow': ['as the crow flies', 'eat crow'],
 'crowd': ['follow the crowd', 'stand out from the crowd'],
 'crunch': ['when it comes to the crunch', 'a credit crunch'],
 'cruel': ['be cruel to be kind', 'cruelty to animals'],
 'crossroads': ['at a crossroads'],
 'crossfire': ['be caught in the crossfire'],
 'cry': ['cry over spilt milk', 'a far cry from', 'a shoulder to cry on',
         'cry wolf', 'cry out for'],
 'crush': ['have a crush on'],
 'crust': ['earn a crust'],
 'crux': ['the crux of the matter'],
 'crystal': ['crystal clear', 'a crystal ball'],
 'cud': ['chew the cud'],
 'cudgel': ['take up the cudgels for', "cudgel one's brains"],
 'cue': ['on cue', "take one's cue from"],
 'cuff': ['off the cuff'],
 'cucumber': ['as cool as a cucumber'],
 'cup': ["not one's cup of tea"],
 'cupboard': ['a skeleton in the cupboard'],
 'cure': ['prevention is better than cure'],
 'curdle': ['blood-curdling'],
 'culture': ['culture shock'],
 'cult': ['the cult of personality', 'a cult following'],
 # 下一批动笔前先列（2026-09-05）
 'curiosity': ['curiosity killed the cat', 'out of curiosity'],
 'curry': ['curry favour with'],
 'curse': ['be cursed with'],
 'curtain': ['bring down the curtain on', 'the final curtain'],
 'custody': ['take into custody', 'in custody'],
 'custom': ['custom-made'],
 'customer': ['the customer is always right'],
 'curve': ['ahead of the curve', 'throw somebody a curve'],
 'current': ['current affairs', 'go against the current'],
 'cut': ['cut back', 'cut down', 'cut in', 'cut it out', 'a cut above',
         'cut both ways', 'cut and dried', 'cut corners', 'cut off',
         'cut out', 'cut somebody some slack'],
 'cute': ['as cute as a button'],
 'cycle': ['a vicious cycle'],
 'cynic': ['a cynical view'],
 # 往下写到哪个字母段，就在这里补哪一段的大词

 # ===== d 段：动笔之前先把清单列好（GOAL 里验证过的做法，省一轮往返）=====
 'day': ['day in day out', 'call it a day', 'the other day', 'these days',
         'day by day', "make somebody's day", 'have a field day',
         'at the end of the day', 'in this day and age', 'save the day',
         "somebody's days are numbered", 'day-to-day', 'one of those days'],
 'damn': ['not give a damn', 'damn all', 'damn with faint praise',
          'as near as damn it'],
 'dam': ['dam up'],
 'damage': ['damage limitation', "what's the damage"],
 'danger': ['in danger of', 'out of danger', 'a danger to', 'danger money'],
 'dare': ['how dare you', "don't you dare", 'I dare say'],
 'dark': ['in the dark', 'a shot in the dark', 'after dark', 'a dark horse',
          'the Dark Ages', 'a dark side'],
 'dash': ['make a dash for', 'cut a dash', 'dash off', "dash somebody's hopes"],
 'date': ['out of date', 'up to date', 'to date', 'date back to', 'date from',
          'a blind date'],
 'dawn': ['dawn on', 'the dawn of', 'from dawn to dusk'],
 'daylight': ['in broad daylight', 'daylight robbery', 'the living daylights'],
 'dead': ['a dead end', 'over my dead body', 'a dead loss', 'drop dead',
          "wouldn't be seen dead", 'dead to the world', 'in the dead of night',
          'a dead ringer for', 'dead in the water', 'a dead heat'],
 'deaf': ['fall on deaf ears', 'turn a deaf ear', 'as deaf as a post'],
 'deal': ['a great deal', 'a good deal', 'big deal', 'deal with', 'deal in',
          'a raw deal', 'a done deal', 'deal a blow', 'cut a deal'],
 'death': ['to death', 'put to death', 'a matter of life and death',
           "catch your death", 'sick to death of', "at death's door",
           'the kiss of death', 'bored to death'],
 'dear': ['oh dear', 'dear me', 'pay dearly'],
 'debt': ['in debt', 'get into debt', 'a debt of gratitude', "in somebody's debt"],
 'decide': ['decide on', 'decide upon', 'decide against'],
 'decision': ['make a decision', 'come to a decision', 'a snap decision'],
 'deck': ['all hands on deck', 'clear the decks', 'hit the deck', 'deck out'],
 'declare': ['declare war', 'anything to declare', 'declare an interest'],
 'decline': ['in decline', 'on the decline', 'decline to comment'],
 'default': ['by default', 'default on'],
 'defeat': ['admit defeat', 'concede defeat'],
 'defence': ["come to somebody's defence", 'in defence of'],
 'defensive': ['on the defensive'],
 'defiance': ['in defiance of'],
 'defy': ['defy description', 'defy belief'],
 'degree': ['to a degree', 'by degrees', 'the third degree'],
 'delay': ['without delay'],
 'delight': ['take delight in', 'a delight'],
 'delve': ['delve into'],
 'demand': ['in demand', 'on demand', 'make demands on'],
 'den': ['a den of iniquity'],
 'denial': ['in denial'],
 'depend': ['depend on', 'it depends', 'depending on'],
 'deny': ['there is no denying', 'deny yourself'],
 'describe': ['describe somebody as'],
 'desert': ['just deserts'],
 'design': ['by design', 'have designs on'],
 'desire': ['leave a lot to be desired'],
 'despair': ['in despair'],
 'detail': ['in detail', 'go into detail'],
 'develop': ['develop into'],
 'devil': ["the devil's advocate", 'speak of the devil', 'between the devil and the deep'],
 'deep': ['in deep water', 'go off the deep end', 'deep down', 'in too deep',
          'take a deep breath', 'still waters run deep', 'deep-seated'],
 'depth': ['in depth', 'out of your depth', 'plumb the depths'],
 'die': ['die out', 'die down', 'die away', 'die off', 'never say die',
         'be dying to', 'be dying for', 'die hard', 'the die is cast',
         'die laughing'],
 'diagnose': ['be diagnosed with'],
 'dial': ['dial a number'],
 'diamond': ['a rough diamond'],
 'dice': ['dice with death', 'no dice'],
 'difficult': ['find it difficult to'],
 'digest': ['digest information'],
 'difference': ['make a difference', 'tell the difference',
                'a world of difference', 'split the difference',
                'with a difference'],
 'dig': ['dig in', 'dig up', 'dig out', 'dig deep', 'dig your heels in',
         'dig your own grave'],
 'dim': ['take a dim view of'],
 'dinner': ['dinner is served'],
 'direct': ['direct debit', 'a direct hit'],
 'dirt': ['dirt cheap', 'dish the dirt'],
 'dirty': ['a dirty look', "somebody's dirty work"],
 'disaster': ['a recipe for disaster', 'a disaster area'],
 'discipline': ['self-discipline'],
 'discretion': ["at somebody's discretion", 'use your discretion'],
 'discuss': ['discuss something with somebody'],
 'disgrace': ['in disgrace', 'a disgrace to'],
 'disguise': ['in disguise', 'a blessing in disguise'],
 'dish': ['dish out', 'dish up', 'dish the dirt', 'do the dishes'],
 'dislike': ['take a dislike to'],
 'dismay': ["to somebody's dismay"],
 'display': ['on display'],
 'disposal': ["at somebody's disposal"],
 'dispute': ['in dispute', 'beyond dispute'],
 'distinction': ['draw a distinction'],
 'distinguish': ['distinguish between'],
 'disturb': ['do not disturb'],
 'distance': ['in the distance', 'keep your distance', 'go the distance',
              'within walking distance', 'distance yourself from'],
 'divide': ['divide up', 'the great divide'],
 'divorce': ['get a divorce'],
 'doctor': ["doctor's orders"],
 'document': ['a legal document'],
 'dole': ['on the dole'],
 'doll': ['dolled up'],
 'domain': ['in the public domain'],
 'dot': ['on the dot', "dot the i's"],
 'do': ['do away with', 'do without', 'do up', 'do in', 'do over', 'do out of',
        'make do', 'have to do with', 'nothing doing', 'that will do',
        'do the trick', 'do or die', 'how do you do', 'do a runner',
        'could do with', 'do somebody a favour'],
 'dog': ["a dog's life", 'go to the dogs', 'let sleeping dogs lie',
         'dog eat dog', 'top dog', "a dog's dinner", 'work like a dog',
         'every dog has its day', 'hair of the dog'],
 'door': ['show somebody the door', 'behind closed doors', 'from door to door',
          "lay something at somebody's door", 'get your foot in the door',
          'next door', 'out of doors', 'answer the door'],
 'double': ['on the double', 'double back', 'double up', 'double-cross',
            'see double', 'a double standard', 'a double take',
            'at the double'],
 'doubt': ['no doubt', 'without a doubt', 'in doubt', 'beyond doubt',
           'give somebody the benefit of the doubt', 'cast doubt on'],
 'down': ['down and out', 'up and down', 'down to earth', 'go down well',
          'let somebody down', 'be down to', 'get down to', 'down the line'],
 'draw': ['draw the line', 'draw a blank', 'draw up', 'draw on', 'draw out',
          'draw in', 'draw back', 'draw attention to', 'the luck of the draw',
          'back to the drawing board'],
 'drag': ['drag your feet', 'drag on'],
 'drain': ['down the drain', 'a drain on'],
 'dream': ['a dream come true', 'in your dreams', 'dream up', 'like a dream',
           'beyond your wildest dreams', 'dream on'],
 'drug': ['be on drugs', 'take drugs'],
 'dwell': ['dwell on', 'dwell upon'],
 'dying': ['be dying for something', 'be dying to do something', 'to your dying day'],
 'dwarf': ['a white dwarf'],
 'duck': ['like water off a duck\'s back', 'take to something like a duck to water',
          'a sitting duck', 'a lame duck', 'duck out'],
 'due': ['due to', 'in due course', 'give somebody their due', 'with all due respect',
         'pay your dues', 'fall due'],
 'dull': ['as dull as ditchwater', 'never a dull moment'],
 'dumb': ['play dumb', 'strike somebody dumb'],
 'dump': ['down in the dumps', 'dump on'],
 'drum': ['drum up', 'bang the drum for'],
 'dress': ['dress up', 'dress down', 'dressed to kill', 'a dress rehearsal',
           'a dressing-down'],
 'drink': ['drink to', 'drink up', 'drink in', 'a stiff drink',
           'drive somebody to drink', 'drink like a fish'],
 'drive': ['drive somebody mad', 'drive a hard bargain', 'drive at',
           'drive away', 'drive out', 'drive somebody up the wall',
           'in the driving seat'],
 'drop': ['drop off', 'drop out', 'drop in', 'drop by', 'drop a hint',
          'a drop in the ocean', 'at the drop of a hat',
          'drop somebody a line', 'let it drop'],
 'dust': ['bite the dust', 'let the dust settle', 'dust off', 'gather dust',
          'when the dust settles'],
 'duty': ['on duty', 'off duty', 'do your duty', 'a duty of care',
          'duty-bound', 'bounden duty', 'do duty as', 'in the line of duty'],
 'have': ['have to', 'have got', 'have got to', 'have something done',
          'have it out with', 'have had it', 'have it in for',
          'have something against', 'have somebody on', 'have somebody in',
          'have somebody back', 'have something out', 'have somebody up',
          'have something on', 'have to do with', 'have a way with',
          'what have you', 'the haves and the have-nots', 'has-been',
          'have done with', 'have it your own way', 'be had'],
 'haven': ['a safe haven', 'a tax haven'],
 'havoc': ['wreak havoc', 'play havoc with', 'cause havoc'],
 'hawk': ['watch somebody like a hawk', 'hawks and doves', 'hawk-eyed'],
 'hay': ['make hay while the sun shines', 'hit the hay', 'a roll in the hay',
         'hay fever'],
 'haystack': ['a needle in a haystack'],
 'haywire': ['go haywire'],
 'hazard': ['hazard a guess', 'a fire hazard', 'a health hazard',
            'hazard lights', 'hazard pay'],
 'haze': ['in a haze'],
 'hazy': ['be hazy about'],
 'harbinger': ['a harbinger of'],
 'hansom': ['a hansom cab'],
 'happenstance': ['by happenstance'],
 'hara-kiri': ['commit hara-kiri'],
 # he- 段 —— 动笔前先列清单（2026-09-21）
 'head': ['head off', 'head for', 'head up', 'come to a head', 'keep your head',
          'lose your head', 'off the top of your head', 'head over heels',
          'go to your head', 'bang your head against a brick wall',
          'head and shoulders above', 'keep your head above water',
          'a head start', 'head-on', 'head-to-head', 'heads or tails',
          'bury your head in the sand', 'have a head for', 'head office',
          'head of state', 'head teacher', 'laugh your head off'],
 'hear': ['hear from', 'hear of', 'hear out', 'hear about',
          'will not hear of it', 'hear something on the grapevine'],
 'heart': ['by heart', 'at heart', 'break somebody\'s heart', 'from the heart',
           'have a heart', 'lose heart', 'take heart', 'set your heart on',
           'a change of heart', 'in your heart of hearts', 'heart and soul',
           'with all your heart', 'to your heart\'s content', 'cross my heart',
           'wear your heart on your sleeve', 'a heart of gold', 'heart-to-heart'],
 'heat': ['in the heat of the moment', 'take the heat out of', 'heat up',
          'the heat is on', 'if you cannot stand the heat'],
 'heaven': ['thank heavens', 'for heaven\'s sake', 'move heaven and earth',
            'in seventh heaven', 'heaven forbid'],
 'heavy': ['heavy going', 'a heavy heart', 'make heavy weather of',
           'heavy-handed', 'heavy industry', 'heavy metal'],
 'heel': ['on the heels of', 'take to your heels', 'dig your heels in',
          'kick your heels', 'head over heels', 'bring somebody to heel',
          'well heeled'],
 'hell': ['go to hell', 'a hell of a', 'like hell', 'all hell broke loose',
          'give somebody hell', 'come hell or high water', 'to hell with',
          'what the hell', 'hell for leather', 'raise hell'],
 'help': ['help out', 'help yourself', 'cannot help doing something',
          'a helping hand', 'help on with', 'help off with'],
 'here': ['here and there', 'here and now', 'neither here nor there',
          'here goes', 'here you are'],
 'hedge': ['hedge your bets', 'hedge against', 'hedge in'],
 'hen': ['a hen party', 'as rare as hen\'s teeth', 'a hen night'],
 'herd': ['ride herd on', 'the herd instinct', 'follow the herd'],
 'hero': ['a hero\'s welcome', 'hero worship', 'an unsung hero'],
 'heroic': ['heroic couplet', 'heroics'],
 'hesitate': ['do not hesitate to', 'he who hesitates is lost',
              'without hesitation', 'have no hesitation in'],
 'hermetic': ['hermetically sealed'],
 'herring': ['red herring', 'herring gull'],
 'hereafter': ['the hereafter'],
 'hew': ['hew to', 'rough-hewn', 'hew out'],
 'hey': ['hey presto'],
 'hide': ['have nothing to hide', 'hide behind', 'hide out', 'hide-and-seek',
          'hide nor hair', 'save your own hide', 'hide your light under a bushel'],
 'hiding': ['in hiding', 'go into hiding', 'a good hiding', 'on a hiding to nothing',
            'hiding place'],
 'hidden': ['a hidden agenda', 'hidden depths', 'a hidden gem'],
 'high': ['high and dry', 'high and mighty', 'high time', 'in high spirits', 'on a high',
          'from on high', 'high and low', 'the high seas', 'on your high horse',
          'riding high', 'hold your head high', 'high on', 'aim high',
          'the moral high ground', 'high season', 'high street'],
 'hill': ['over the hill', 'as old as the hills', 'head for the hills',
          'up hill and down dale', 'a hill of beans', 'king of the hill'],
 'hilt': ['to the hilt'],
 'himself': ['by himself', 'not himself'],
 'hinge': ['hinge on', 'off its hinges'],
 'hint': ['drop a hint', 'take the hint', 'a hint of', 'hint at'],
 'hip': ['shoot from the hip', 'joined at the hip', 'hip, hip, hooray'],
 'hire': ['for hire', 'hire out', 'hire and fire'],
 'history': ['make history', 'go down in history', 'the rest is history',
             'be history', 'history repeats itself', 'ancient history',
             'a history of'],
 'hit': ['hit it off', 'hit the roof', 'hit the nail on the head', 'hit the road',
         'hit the sack', 'hit the jackpot', 'hit the headlines', 'hit home',
         'hit the spot', 'hit the ground running', 'hit rock bottom',
         'hit below the belt', 'hit back', 'hit out at', 'hit on', 'hit upon',
         'hit the bottle', 'hit the big time', 'hit a nerve', 'hit the books',
         'hit the deck', 'a direct hit', 'make a hit with', 'hit and run'],
 'hitch': ['get hitched', 'without a hitch', 'a technical hitch', 'hitch a lift',
           'hitch a ride', 'hitch up'],
 'hoarse': ['shout yourself hoarse'],
 'hobby': ['hobby horse'],
 'hock': ['in hock'],
 'hoax': ['a hoax call'],
 'hold': ['hold your breath', 'hold your tongue', 'hold your own', 'hold the line',
          'hold true', 'hold water', 'hold fire', 'hold court', 'hold the fort',
          'hold sway', 'hold all the cards', 'hold your horses', 'get hold of',
          'on hold', 'no holds barred', 'hold a candle to', 'hold the key to',
          'hold still', 'hold office', 'hold hands', 'take hold'],
 'hole': ['in the hole', 'pick holes in', 'a square peg in a round hole',
          'hole up', 'like a hole in the head', 'burn a hole in your pocket',
          'dig yourself into a hole', 'an ace in the hole', 'hole in one'],
 'holiday': ['on holiday', 'go on holiday', 'bank holiday', "a busman's holiday",
             'the holidays'],
 'hollow': ['beat somebody hollow', 'hollow out', 'ring hollow', 'a hollow victory'],
 'holy': ['holy of holies', 'holier-than-thou', 'holy water'],
 'home': ['at home', 'make yourself at home', 'feel at home', 'home and dry',
          'home sweet home', 'a home from home', 'close to home',
          'nothing to write home about', 'bring something home to', 'drive home',
          'charity begins at home', 'home in on', 'leave home', 'a home truth',
          'home town', 'strike home'],
 'homework': ['do your homework'],
 'honest': ['to be honest', 'honest to God', 'make an honest woman of', 'honest broker'],
 'honesty': ['in all honesty', 'honesty is the best policy'],
 'honeymoon': ['the honeymoon is over', 'honeymoon period'],
 'honour': ['in honour of', 'guest of honour', 'a point of honour', 'do the honours',
            'your Honour', 'honour among thieves', 'word of honour', 'maid of honour',
            'with honours', 'on my honour'],
 'hook': ['off the hook', 'by hook or by crook', 'hook, line and sinker',
          'sling your hook', 'let somebody off the hook', 'get your hooks into'],
 'hoof': ['on the hoof'],
 'hoot': ['not give a hoot', 'a hoot'],
 'hope': ['hope against hope', 'hope for the best', 'not a hope', 'pin your hopes on',
          'raise hopes', 'dash hopes', 'in the hope of', 'live in hope', 'some hope'],
 'hop': ['hop it', 'on the hop', 'hop to it', 'hop in'],
 'horizon': ['on the horizon', 'broaden your horizons'],
 'horn': ['blow your own horn', 'lock horns', 'on the horns of a dilemma',
          'take the bull by the horns', 'pull in your horns'],
 'horror': ['horror of horrors', 'in horror'],
 'horse': ["straight from the horse's mouth", 'flog a dead horse', 'eat like a horse',
           'a dark horse', 'put the cart before the horse', 'horses for courses',
           'look a gift horse in the mouth', 'wild horses', 'change horses in midstream',
           'a one-horse town', 'on horseback', 'fall off a horse', 'ride a horse'],
 'hospital': ['in hospital', 'in the hospital'],
 'host': ['play host to', 'a host of'],
 'hot': ['hot and bothered', 'in hot water', 'blow hot and cold', 'hot under the collar',
         'hot on the heels of', 'be hot on', 'hot off the press', 'not so hot', 'hot stuff',
         'a hot potato', 'hot air', 'sell like hot cakes', 'have the hots for',
         'in the hot seat', 'too hot to handle'],
 'hour': ['at the eleventh hour', 'the small hours', 'on the hour', 'after hours',
          'by the hour', 'hour after hour', 'the man of the hour', 'rush hour',
          'for hours on end'],
 'house': ['on the house', 'bring the house down', 'get on like a house on fire',
           'put your house in order', 'safe as houses', 'house of cards', 'keep house',
           'set up house', 'move house', 'a full house', 'people who live in glass houses'],
 'household': ['household name'],
 'how': ['how about', 'how come', 'how do you do', 'and how', 'how so', 'how dare you',
         'how on earth', "how's that", 'how about that', 'how-to'],
 'howl': ['howl down', 'howls of laughter', 'howls of protest'],
 'hub': ['the hub of'],
 'hue': ['hue and cry'],
 'huff': ['in a huff', 'huff and puff'],
 'hug': ['give somebody a hug', 'a bear hug', 'hug the coast'],
 'human': ['human nature', 'only human', 'human rights', 'the human race', 'human error'],
 'humble': ['eat humble pie', 'in my humble opinion'],
 'humour': ['a sense of humour', 'in a good humour', 'humour somebody'],
 'hump': ['over the hump', 'get the hump'],
 'hungry': ['go hungry', 'hungry for'],
 'hunt': ['hunt down', 'hunt for', 'job-hunting', 'go hunting', 'hunt high and low'],
 'hurry': ['in a hurry', 'hurry up', 'in no hurry', 'hurry on'],
 'hurt': ["hurt somebody's feelings", 'it would not hurt', 'feel hurt'],
 'hush': ['hush up', 'hush money'],
}
def main():
    B = {}
    for h, L in ap.entries(): B.setdefault(h, []).extend(L)
    allB = fold(' '.join(l for v in B.values() for l in v))
    miss = []; tot = 0; skipped = []
    for h, items in sorted(CHECK.items()):
        if h not in B: skipped.append(h); continue
        body = fold(' '.join(B[h]))
        for it in items:
            tot += 1
            f = fold(it)
            if f not in body and f not in allB: miss.append((h, it))
    print('\n查 %d 个大词的 %d 条习语，B 里缺 %d 条' % (len(CHECK) - len(skipped), tot, len(miss)))
    if skipped: print('  （还没写到的词条，跳过：%s）' % ' '.join(skipped))
    cur = None
    for h, it in miss:
        if h != cur: print('    %s' % h); cur = h
        print('        缺：%s' % it)
    if not miss: print('  ✅ 清单里的习语都收了')
    return 1 if miss else 0

if __name__ == '__main__':
    sys.exit(main())
