#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""查大词的习语收全了没有。

audit-ab 只查得出「A 教过而 B 没有」的，A 只收 3002 个高频词，
两表共有的才 517 条 —— A 没收的词依然没有尺子。corner 漏掉的
turn the corner / cut corners / just around the corner /
out of the corner of one's eye 就属于这一类，是手工翻出来的。

这个脚本把「知识」和「核对」分开：清单由人写（下面的 CHECK），
机器负责查 B 里有没有。写完一个字母段的大词，就往 CHECK 里
补一批，跑一遍，缺什么补什么。
首跑（2026-09-05）查 23 个 c 段大词的 101 条习语，缺 34 条，已全部补上。

用法：python3 scripts/audit-idioms.py
"""
import sys, re, unicodedata, importlib.util as u
spec = u.spec_from_file_location('ap', 'scripts/audit-padding.py')
ap = u.module_from_spec(spec); spec.loader.exec_module(ap)

def fold(s):
    s = unicodedata.normalize('NFD', s)
    s = ''.join(c for c in s if unicodedata.category(c) != 'Mn')
    return re.sub(r'[^a-z0-9]+', ' ', s.lower()).strip()

CHECK = {
 'fling': ['have a fling'],
 'flip': ['flip out', 'flip through'],
 'float': ['float an idea'],
 'flog': ['flog a dead horse'],
 'flesh': ['in the flesh', 'flesh out', 'flesh and blood'],
 'flight': ['take flight', 'a flight of stairs'],
 'flea': ['a flea market', 'a flea in your ear'],
 'flavour': ['add flavour'],
 'flat': ['flat out', 'flat broke'],
 'flattery': ['flattery will get you nowhere'],
 'flame': ['burst into flames', 'go up in flames', 'an old flame'],
 'flash': ['in a flash', 'a flash in the pan'],
 'flap': ['in a flap'],
 'flag': ['fly the flag', 'flag down'],
 'flair': ['have a flair for'],
 'flak': ['take flak'],
 'fit': ['see fit', 'fit in', 'keep fit', 'fit for purpose'],
 'fix': ['in a fix', 'a quick fix'],
 'fist': ['make a good fist of', 'hand over fist'],
 'first': ['at first', 'first of all', 'first come, first served'],
 'fish': ['a fish out of water', 'fish and chips'],
 'fire': ['catch fire', 'set fire to', 'on fire', 'under fire', 'open fire', 'play with fire'],
 'fine': ['cut it fine', 'a fine line'],
 'finger': ['keep your fingers crossed', 'put your finger on', 'point the finger at'],
 'fingertip': ['at your fingertips'],
 'find': ['find out', 'find your feet'],
 'filter': ['filter out', 'filter through'],
 'file': ['on file', 'file for', 'in single file'],
 'fill': ['fill in', 'fill up', 'fill the bill', 'eat your fill'],
 'film': ['a film star'],
 'fight': ['put up a fight', 'fight a losing battle', 'fight back', 'fight off'],
 'figure': ['figure out', 'a figure of speech', 'cut a figure'],
 'fig': ['not give a fig'],
 'fiddle': ['on the fiddle', 'play second fiddle'],
 'field': ['take the field', 'a level playing field', 'play the field'],
 'few': ['quite a few', 'a good few', 'few and far between'],
 'fever': ['a high fever', 'run a fever'],
 'fence': ['sit on the fence', 'mend fences'],
 'fettle': ['in fine fettle'],
 'fetch': ['fetch and carry'],
 'fear': ['for fear of', 'no fear', 'fear the worst'],
 'feast': ['feast your eyes on'],
 'feather': ['a feather in your cap', 'as light as a feather', 'feather your nest'],
 'feel': ['feel like', 'feel free', 'feel your age', 'get the feel of'],
 'feed': ['feed up', 'off your feed'],
 'fee': ['a flat fee'],
 'fault': ['find fault with', 'at fault', 'to a fault'],
 'favour': ['in favour of', 'do somebody a favour', 'curry favour'],
 'fat': ['chew the fat', 'a fat lot of good'],
 'fate': ['tempt fate', "seal somebody's fate"],
 'father': ['the father of'],
 'fashion': ['in fashion', 'out of fashion', 'after a fashion'],
 'fast': ['fast asleep', 'play fast and loose', 'hold fast'],
 'family': ['run in the family', 'start a family', 'a family tree'],
 'famous': ['famous last words'],
 'fancy': ['take a fancy to', 'tickle your fancy', 'fancy dress', 'fancy that'],
 'far': ['as far as', 'by far', 'so far', 'far from', 'far and wide'],
 'face': ['keep a straight face', 'lose face', 'save face', 'face to face',
          'in the face of', 'on the face of it', "face the music", 'pull a face'],
 'fact': ['in fact', 'as a matter of fact', 'the fact of the matter', 'facts and figures'],
 'fail': ['without fail'],
 'fair': ['fair enough', 'fair and square', "it's not fair", 'more than your fair share'],
 'faith': ['in good faith', 'have faith in', 'break faith with'],
 'fall': ['fall in love', 'fall short of', 'fall into place', 'fall flat', 'fall apart'],
 'eye': ['keep an eye on', 'see eye to eye', 'turn a blind eye', "catch somebody's eye",
         'an eye for an eye', 'have your eye on', 'the eye of the storm'],
 'eyebrow': ['raise an eyebrow'],
 'eyelid': ['not bat an eyelid'],
 'eyelash': ['flutter your eyelashes'],
 'extreme': ['in the extreme', 'go to extremes', 'take something to extremes'],
 'explode': ['explode a myth'],
 'explore': ['explore every avenue'],
 'express': ['express yourself', 'express an interest'],
 'expression': ['freedom of expression', 'find expression in'],
 'extend': ['extend an invitation'],
 'extent': ['to some extent', 'to a certain extent', 'to a large extent', 'to what extent'],
 'expect': ['be expecting', 'what do you expect'],
 'expectation': ['live up to expectations', 'contrary to expectation', 'exceed expectations'],
 'expense': ['at the expense of', "at somebody's expense", 'go to the expense of', 'spare no expense'],
 'experience': ['from experience', 'in my experience'],
 'explain': ['explain yourself', 'explain away'],
 'each': ['each and every'],
 'exercise': ['take exercise', 'exercise your right', 'a paper exercise'],
 'exhaust': ['exhaust fumes', 'be exhausted'],
 'exhibit': ['be on exhibit'],
 'exist': ['cease to exist'],
 'example': ['for example', 'set an example', 'make an example of', "follow somebody's example"],
 'exception': ['with the exception of', 'without exception', 'make an exception'],
 'excuse': ['make excuses', 'excuse me'],
 'exchange': ['in exchange for'],
 'even': ['break even', 'even so', 'even though', 'get even', 'even if'],
 'ever': ['ever since', 'hardly ever', 'for ever'],
 'every': ['every other', 'every now and then', 'every bit as'],
 'event': ['in the event of', 'at all events', 'in any event'],
 'evidence': ['give evidence', 'be in evidence'],
 'evil': ['the lesser of two evils', 'speak evil of'],
 'essence': ['in essence', 'of the essence'],
 'establish': ['establish yourself'],
 'esteem': ['hold somebody in high esteem', 'self-esteem'],
 'err': ['err on the side of'],
 'error': ['trial and error', 'in error', 'a margin of error'],
 'errand': ['run an errand', "a fool's errand"],
 'equal': ['on equal terms', 'be equal to', 'all things being equal', 'have no equal'],
 'equation': ['part of the equation'],
 'end': ['in the end', 'at the end of the day', 'make ends meet', 'come to an end',
         'no end of', 'end up'],
 'enough': ['enough is enough', 'fair enough', 'sure enough'],
 'enjoy': ['enjoy yourself'],
 'entrance': ['make an entrance'],
 'embarrassment': ['an embarrassment of riches'],
 'emergency': ['in an emergency', 'a state of emergency'],
 'emphasis': ['put emphasis on', 'the emphasis is on'],
 'empty': ['on an empty stomach'],
 'elbow': ['elbow room', 'elbow grease', 'rub elbows with', 'give somebody the elbow',
           'elbow your way'],
 'element': ['in your element', 'brave the elements', 'the elements'],
 'else': ['or else', 'something else', 'somebody else'],
 'elephant': ['a white elephant', 'the elephant in the room'],
 'eleventh': ['at the eleventh hour'],
 'effect': ['take effect', 'come into effect', 'in effect', 'to that effect',
            'put something into effect'],
 'egg': ['put all your eggs in one basket', 'a bad egg', 'have egg on your face',
         'egg somebody on'],
 'either': ['either way', 'either... or'],
 'ebb': ['the ebb and flow', 'at a low ebb'],
 'echo': ['echoes of'],
 'eclipse': ['in eclipse'],
 'economy': ['economies of scale', 'a false economy'],
 'edge': ['on edge', 'on the edge of', 'have the edge over', 'take the edge off',
          'edge out', 'set your teeth on edge'],
 'educate': ['educate somebody about something'],
 'ear': ['play it by ear', 'be all ears', 'go in one ear and out the other',
         "have somebody's ear", 'keep your ear to the ground', 'up to your ears in',
         'music to your ears', 'turn a deaf ear'],
 'early': ['an early bird', 'at the earliest', 'early days', 'bright and early', 'early on'],
 'earn': ['earn a living', 'earn your keep'],
 'earth': ['cost the earth', 'down to earth', 'on earth', 'move heaven and earth',
           'run somebody to earth'],
 'ease': ['at ease', 'ill at ease', 'with ease', 'put somebody at their ease'],
 'easy': ['take it easy', 'easier said than done', 'go easy on', 'easy come, easy go',
          'easy does it', 'free and easy', 'within easy reach'],
 'eat': ['eat your words', 'eat out of somebody\'s hand', "what's eating",
         'eat like a horse', 'eat your heart out'],

 'call': ['call it a day', 'call the shots', 'call off', 'call for', 'on call',
          'a close call', "call somebody's bluff", 'call in'],
 'carry': ['carry on', 'carry out', 'get carried away', 'carry weight', 'carry the can'],
 'case': ['in case', 'in any case', 'in that case', 'a case in point', 'make a case for'],
 'cast': ['cast doubt on', 'cast a shadow', 'cast off', "cast one's mind back"],
 'catch': ['catch on', 'catch up', 'catch out', 'catch fire', "catch somebody's eye"],
 'chance': ['by chance', 'take a chance', 'stand a chance', 'the chances are',
            'a fighting chance'],
 'change': ['change hands', "change one's mind", 'small change', 'a change of heart',
            'for a change'],
 'check': ['check in', 'check out', 'check up on', 'keep in check', 'a rain check'],
 'chip': ['chip in', "a chip on one's shoulder", 'when the chips are down'],
 'clear': ['clear up', 'clear out', 'clear the air', 'in the clear', 'steer clear of',
           'clear-cut'],
 'close': ['close down', 'close in', 'a close shave', 'close ranks', 'behind closed doors'],
 'cold': ['cold feet', 'in cold blood', 'the cold shoulder', 'out in the cold', 'cold turkey'],
 'come': ['come across', 'come up with', 'come to terms with', 'come what may',
          'come clean', 'come of age', 'come around'],
 'company': ['keep somebody company', 'part company', 'in good company'],
 'contact': ['make contact', 'lose contact'],
 'control': ['out of control', 'under control', 'take control', 'lose control'],
 'cool': ["lose one's cool", 'a cool million', 'be cool with', 'cool it'],
 'corn': ['corn on the cob'],
 'corner': ['turn the corner', 'cut corners', 'just around the corner',
            "out of the corner of one's eye", 'a corner shop'],
 'count': ["count one's blessings", 'count for nothing', 'at the last count'],
 # course 与 cover 写到了（2026-09-05），加回清单
 'course': ['of course', 'in due course', 'a matter of course', 'run its course',
            'on course', 'off course'],
 'cover': ['cover up', 'cover for', 'under cover', "cover one's tracks",
           'from cover to cover'],
 'courage': ['pluck up courage', 'Dutch courage',
             "the courage of one's convictions"],
 'cow': ['till the cows come home', 'a sacred cow', 'have a cow'],
 'court': ['take somebody to court', 'court disaster', 'go to court'],
 # cr 段（2026-09-05 写到 crevice）
 'crack': ['crack down on', 'crack up', 'at the crack of dawn',
           'crack a joke', 'have a crack at'],
 'crash': ['crash a party', 'crash into'],
 'crazy': ['be crazy about', 'like crazy'],
 'cream': ['the cream of the crop', 'cream off'],
 'credit': ['take credit for', 'give somebody credit for',
            'on credit', 'in credit'],
 'creep': ['give somebody the creeps', 'creep up on'],
 'crest': ['crestfallen', 'the crest of a wave'],
 'cricket': ['not cricket'],
 'crime': ['commit a crime', 'organized crime'],
 'critical': ['be critical of', 'critical thinking', 'in a critical condition'],
 'crocodile': ['crocodile tears'],
 'crop': ['crop up', 'come a cropper'],
 'crook': ['the crook of one s arm'],
 'cross': ["cross one's mind", 'cross swords with', 'at cross purposes',
           'cross out', 'be cross with'],
 'crow': ['as the crow flies', 'eat crow'],
 'crowd': ['follow the crowd', 'stand out from the crowd'],
 'crunch': ['when it comes to the crunch', 'a credit crunch'],
 'cruel': ['be cruel to be kind', 'cruelty to animals'],
 'crossroads': ['at a crossroads'],
 'crossfire': ['be caught in the crossfire'],
 'cry': ['cry over spilt milk', 'a far cry from', 'a shoulder to cry on',
         'cry wolf', 'cry out for'],
 'crush': ['have a crush on'],
 'crust': ['earn a crust'],
 'crux': ['the crux of the matter'],
 'crystal': ['crystal clear', 'a crystal ball'],
 'cud': ['chew the cud'],
 'cudgel': ['take up the cudgels for', "cudgel one's brains"],
 'cue': ['on cue', "take one's cue from"],
 'cuff': ['off the cuff'],
 'cucumber': ['as cool as a cucumber'],
 'cup': ["not one's cup of tea"],
 'cupboard': ['a skeleton in the cupboard'],
 'cure': ['prevention is better than cure'],
 'curdle': ['blood-curdling'],
 'culture': ['culture shock'],
 'cult': ['the cult of personality', 'a cult following'],
 # 下一批动笔前先列（2026-09-05）
 'curiosity': ['curiosity killed the cat', 'out of curiosity'],
 'curry': ['curry favour with'],
 'curse': ['be cursed with'],
 'curtain': ['bring down the curtain on', 'the final curtain'],
 'custody': ['take into custody', 'in custody'],
 'custom': ['custom-made'],
 'customer': ['the customer is always right'],
 'curve': ['ahead of the curve', 'throw somebody a curve'],
 'current': ['current affairs', 'go against the current'],
 'cut': ['cut back', 'cut down', 'cut in', 'cut it out', 'a cut above',
         'cut both ways', 'cut and dried', 'cut corners', 'cut off',
         'cut out', 'cut somebody some slack'],
 'cute': ['as cute as a button'],
 'cycle': ['a vicious cycle'],
 'cynic': ['a cynical view'],
 # 往下写到哪个字母段，就在这里补哪一段的大词

 # ===== d 段：动笔之前先把清单列好（GOAL 里验证过的做法，省一轮往返）=====
 'day': ['day in day out', 'call it a day', 'the other day', 'these days',
         'day by day', "make somebody's day", 'have a field day',
         'at the end of the day', 'in this day and age', 'save the day',
         "somebody's days are numbered", 'day-to-day', 'one of those days'],
 'damn': ['not give a damn', 'damn all', 'damn with faint praise',
          'as near as damn it'],
 'dam': ['dam up'],
 'damage': ['damage limitation', "what's the damage"],
 'danger': ['in danger of', 'out of danger', 'a danger to', 'danger money'],
 'dare': ['how dare you', "don't you dare", 'I dare say'],
 'dark': ['in the dark', 'a shot in the dark', 'after dark', 'a dark horse',
          'the Dark Ages', 'a dark side'],
 'dash': ['make a dash for', 'cut a dash', 'dash off', "dash somebody's hopes"],
 'date': ['out of date', 'up to date', 'to date', 'date back to', 'date from',
          'a blind date'],
 'dawn': ['dawn on', 'the dawn of', 'from dawn to dusk'],
 'daylight': ['in broad daylight', 'daylight robbery', 'the living daylights'],
 'dead': ['a dead end', 'over my dead body', 'a dead loss', 'drop dead',
          "wouldn't be seen dead", 'dead to the world', 'in the dead of night',
          'a dead ringer for', 'dead in the water', 'a dead heat'],
 'deaf': ['fall on deaf ears', 'turn a deaf ear', 'as deaf as a post'],
 'deal': ['a great deal', 'a good deal', 'big deal', 'deal with', 'deal in',
          'a raw deal', 'a done deal', 'deal a blow', 'cut a deal'],
 'death': ['to death', 'put to death', 'a matter of life and death',
           "catch your death", 'sick to death of', "at death's door",
           'the kiss of death', 'bored to death'],
 'dear': ['oh dear', 'dear me', 'pay dearly'],
 'debt': ['in debt', 'get into debt', 'a debt of gratitude', "in somebody's debt"],
 'decide': ['decide on', 'decide upon', 'decide against'],
 'decision': ['make a decision', 'come to a decision', 'a snap decision'],
 'deck': ['all hands on deck', 'clear the decks', 'hit the deck', 'deck out'],
 'declare': ['declare war', 'anything to declare', 'declare an interest'],
 'decline': ['in decline', 'on the decline', 'decline to comment'],
 'default': ['by default', 'default on'],
 'defeat': ['admit defeat', 'concede defeat'],
 'defence': ["come to somebody's defence", 'in defence of'],
 'defensive': ['on the defensive'],
 'defiance': ['in defiance of'],
 'defy': ['defy description', 'defy belief'],
 'degree': ['to a degree', 'by degrees', 'the third degree'],
 'delay': ['without delay'],
 'delight': ['take delight in', 'a delight'],
 'delve': ['delve into'],
 'demand': ['in demand', 'on demand', 'make demands on'],
 'den': ['a den of iniquity'],
 'denial': ['in denial'],
 'depend': ['depend on', 'it depends', 'depending on'],
 'deny': ['there is no denying', 'deny yourself'],
 'describe': ['describe somebody as'],
 'desert': ['just deserts'],
 'design': ['by design', 'have designs on'],
 'desire': ['leave a lot to be desired'],
 'despair': ['in despair'],
 'detail': ['in detail', 'go into detail'],
 'develop': ['develop into'],
 'devil': ["the devil's advocate", 'speak of the devil', 'between the devil and the deep'],
 'deep': ['in deep water', 'go off the deep end', 'deep down', 'in too deep',
          'take a deep breath', 'still waters run deep', 'deep-seated'],
 'depth': ['in depth', 'out of your depth', 'plumb the depths'],
 'die': ['die out', 'die down', 'die away', 'die off', 'never say die',
         'be dying to', 'be dying for', 'die hard', 'the die is cast',
         'die laughing'],
 'diagnose': ['be diagnosed with'],
 'dial': ['dial a number'],
 'diamond': ['a rough diamond'],
 'dice': ['dice with death', 'no dice'],
 'difficult': ['find it difficult to'],
 'digest': ['digest information'],
 'difference': ['make a difference', 'tell the difference',
                'a world of difference', 'split the difference',
                'with a difference'],
 'dig': ['dig in', 'dig up', 'dig out', 'dig deep', 'dig your heels in',
         'dig your own grave'],
 'dim': ['take a dim view of'],
 'dinner': ['dinner is served'],
 'direct': ['direct debit', 'a direct hit'],
 'dirt': ['dirt cheap', 'dish the dirt'],
 'dirty': ['a dirty look', "somebody's dirty work"],
 'disaster': ['a recipe for disaster', 'a disaster area'],
 'discipline': ['self-discipline'],
 'discretion': ["at somebody's discretion", 'use your discretion'],
 'discuss': ['discuss something with somebody'],
 'disgrace': ['in disgrace', 'a disgrace to'],
 'disguise': ['in disguise', 'a blessing in disguise'],
 'dish': ['dish out', 'dish up', 'dish the dirt', 'do the dishes'],
 'dislike': ['take a dislike to'],
 'dismay': ["to somebody's dismay"],
 'display': ['on display'],
 'disposal': ["at somebody's disposal"],
 'dispute': ['in dispute', 'beyond dispute'],
 'distinction': ['draw a distinction'],
 'distinguish': ['distinguish between'],
 'disturb': ['do not disturb'],
 'distance': ['in the distance', 'keep your distance', 'go the distance',
              'within walking distance', 'distance yourself from'],
 'divide': ['divide up', 'the great divide'],
 'divorce': ['get a divorce'],
 'doctor': ["doctor's orders"],
 'document': ['a legal document'],
 'dole': ['on the dole'],
 'doll': ['dolled up'],
 'domain': ['in the public domain'],
 'dot': ['on the dot', "dot the i's"],
 'do': ['do away with', 'do without', 'do up', 'do in', 'do over', 'do out of',
        'make do', 'have to do with', 'nothing doing', 'that will do',
        'do the trick', 'do or die', 'how do you do', 'do a runner',
        'could do with', 'do somebody a favour'],
 'dog': ["a dog's life", 'go to the dogs', 'let sleeping dogs lie',
         'dog eat dog', 'top dog', "a dog's dinner", 'work like a dog',
         'every dog has its day', 'hair of the dog'],
 'door': ['show somebody the door', 'behind closed doors', 'from door to door',
          "lay something at somebody's door", 'get your foot in the door',
          'next door', 'out of doors', 'answer the door'],
 'double': ['on the double', 'double back', 'double up', 'double-cross',
            'see double', 'a double standard', 'a double take',
            'at the double'],
 'doubt': ['no doubt', 'without a doubt', 'in doubt', 'beyond doubt',
           'give somebody the benefit of the doubt', 'cast doubt on'],
 'down': ['down and out', 'up and down', 'down to earth', 'go down well',
          'let somebody down', 'be down to', 'get down to', 'down the line'],
 'draw': ['draw the line', 'draw a blank', 'draw up', 'draw on', 'draw out',
          'draw in', 'draw back', 'draw attention to', 'the luck of the draw',
          'back to the drawing board'],
 'drag': ['drag your feet', 'drag on'],
 'drain': ['down the drain', 'a drain on'],
 'dream': ['a dream come true', 'in your dreams', 'dream up', 'like a dream',
           'beyond your wildest dreams', 'dream on'],
 'drug': ['be on drugs', 'take drugs'],
 'dwell': ['dwell on', 'dwell upon'],
 'dying': ['be dying for something', 'be dying to do something', 'to your dying day'],
 'dwarf': ['a white dwarf'],
 'duck': ['like water off a duck\'s back', 'take to something like a duck to water',
          'a sitting duck', 'a lame duck', 'duck out'],
 'due': ['due to', 'in due course', 'give somebody their due', 'with all due respect',
         'pay your dues', 'fall due'],
 'dull': ['as dull as ditchwater', 'never a dull moment'],
 'dumb': ['play dumb', 'strike somebody dumb'],
 'dump': ['down in the dumps', 'dump on'],
 'dust': ['bite the dust', 'let the dust settle', 'gather dust', 'dust off',
          'when the dust settles'],
 'duty': ['on duty', 'off duty', 'do duty as', 'in the line of duty', 'duty of care'],
 'drum': ['drum up', 'bang the drum for'],
 'dress': ['dress up', 'dress down', 'dressed to kill', 'a dress rehearsal',
           'a dressing-down'],
 'drink': ['drink to', 'drink up', 'drink in', 'a stiff drink',
           'drive somebody to drink', 'drink like a fish'],
 'drive': ['drive somebody mad', 'drive a hard bargain', 'drive at',
           'drive away', 'drive out', 'drive somebody up the wall',
           'in the driving seat'],
 'drop': ['drop off', 'drop out', 'drop in', 'drop by', 'drop a hint',
          'a drop in the ocean', 'at the drop of a hat',
          'drop somebody a line', 'let it drop'],
 'dust': ['bite the dust', 'let the dust settle', 'dust off', 'gather dust'],
 'duty': ['on duty', 'off duty', 'do your duty', 'a duty of care',
          'duty-bound', 'bounden duty'],
}

def main():
    B = {}
    for h, L in ap.entries(): B.setdefault(h, []).extend(L)
    allB = fold(' '.join(l for v in B.values() for l in v))
    miss = []; tot = 0; skipped = []
    for h, items in sorted(CHECK.items()):
        if h not in B: skipped.append(h); continue
        body = fold(' '.join(B[h]))
        for it in items:
            tot += 1
            f = fold(it)
            if f not in body and f not in allB: miss.append((h, it))
    print('\n查 %d 个大词的 %d 条习语，B 里缺 %d 条' % (len(CHECK) - len(skipped), tot, len(miss)))
    if skipped: print('  （还没写到的词条，跳过：%s）' % ' '.join(skipped))
    cur = None
    for h, it in miss:
        if h != cur: print('    %s' % h); cur = h
        print('        缺：%s' % it)
    if not miss: print('  ✅ 清单里的习语都收了')
    return 1 if miss else 0

if __name__ == '__main__':
    sys.exit(main())
